version: '3.8'
services:
  vue:
    build:
      context: ./vue/docker
    image: iot_etage/vue
    container_name: vue
    hostname: vue
    restart: always
    depends_on:
      - 'java'
    healthcheck:
      test: 'curl -f http://localhost:8080 -k'
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./vue/src/iot_etage:/app
    environment:
      - VUE_APP_ENV=prod
      - VUE_APP_BASE_URL='http://localhost:8080'
      - VUE_APP_BACKEND_URL=http://localhost:8090
      - CHOKIDAR_USEPOLLING=true
    networks:
      iot-network:
        ipv4_address: 192.16.1.10
    command: '/app/node_modules/.bin/vue-cli-service serve --host 0.0.0.0 --port 8080'
    #logging:
      #driver: 'none'

  java:
    build:
      context: ./java/docker
    image: iot_etage/java
    container_name: java
    hostname: java
    restart: always
    depends_on:
      - 'postgres'
      - 'mosquitto'
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - ./java/src/IoTEtage/:/app/
      - java-maven-local-repository:/root/.m2
    environment:
      - ENV=prod
      - REBUILD=true
    networks:
      iot-network:
        ipv4_address: 192.16.1.30
    command: 'java -jar target/iot_etage-0.0.1-SNAPSHOT.jar'

  mosquitto:
    build:
      context: ./mosquitto/docker
    image: iot_etage/mosquitto
    container_name: mosquitto
    hostname: mosquitto
    restart: always
    #healthcheck:
    #test: 'curl -X GET "http://localhost:1883/iot/about"'
    ports:
      - '1884:1883'
      - '1885:1884'
      - '8884:8883'
      #- '9001:9001'
    volumes:
      - ./mosquitto/configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - ENV=prod
    networks:
      iot-network:
        ipv4_address: 192.16.1.40

  postgres:
    build:
      context: ./postgres/docker
    image: iot_etage/postgres
    container_name: postgres
    hostname: postgres
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/SQL-Scripts:/scripts
    environment:
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
      - POSTGRES_PASSWORD=admin_password
      - ENV=prod
    networks:
      iot-network:
        ipv4_address: 192.16.1.50

networks:
  iot-network:
    name: iot-network
    ipam:
      driver: default
      config:
        - subnet: '192.16.1.0/24'

volumes:
  postgres-data:
  java-maven-local-repository:
