version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
    image: iot_etage/nginx-prod
    container_name: nginx-prod
    hostname: nginx-prod
    restart: on-failure
    depends_on:
      - 'java'
    healthcheck:
      test: curl -f http://localhost:80
      interval: 10s
    ports:
      - '443:443'
      - '80:80'
      - '81:81'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./vue/src/iot_etage:/app/vue-dev
      - ./nginx/data:/app/prod
    environment:
      - ENV=prod
      - VUE_APP_BASE_URL='http://localhost'
      - VUE_APP_BACKEND_URL=http://localhost/api
    networks:
      iot-network:
        ipv4_address: 192.16.1.100
    # command: /bin/bash
    # tty: yes

  java:
    build:
      context: ./java/docker-prod
    image: iot_etage/java-prod
    container_name: java-prod
    hostname: java-prod
    restart: on-failure
    depends_on:
      - 'postgres'
    volumes:
      - ./java/src/IoTEtage/:/app
    environment:
      - ENV=prod
    networks:
      iot-network:
        ipv4_address: 192.16.1.30

  mosquitto:
    build:
      context: ./mosquitto/docker
    image: iot_etage/mosquitto
    container_name: mosquitto
    hostname: mosquitto
    restart: always
    ports:
      - '1883:1883'
      - '1884:1883'
      - '8883:8883'
      - '8884:8883'
    volumes:
      - ./mosquitto/dev/configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/dev/data:/mosquitto/data
      - ./mosquitto/dev/log:/mosquitto/log
    environment:
      - ENV=prod
    networks:
      iot-network:
        ipv4_address: 192.16.1.40

  postgres:
    build:
      context: ./postgres/docker
    image: postgres-prod
    container_name: postgres-prod
    hostname: postgres-prod
    restart: on-failure
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    environment:
      - ENV=prod
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
      - POSTGRES_PASSWORD=admin_password
    networks:
      iot-network:
        ipv4_address: 192.16.1.50

networks:
  iot-network:
    name: iot-network
    ipam:
      driver: default
      config:
        - subnet: '192.16.1.0/24'

volumes:
  postgres-data-prod:
