GET http://localhost:8090
###
GET http://localhost:8090/events HTTP/1.1
Content-Type: application/json
###
GET http://192.16.1.30:8090/events HTTP/1.1
Content-Type: application/json
###
http://192.16.1.30:8090

###
GET http://localhost:8090/events HTTP/1.1
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJLaXJpbGw1IiwiYXV0aCI6eyJhdXRob3JpdHkiOiJPRkZJQ0VfV09SS0VSIn0sImlhdCI6MTYxMTA3NzE1OCwiZXhwIjoxNjExMDgwNzU4fQ.P0retkczHq7TtisI7IwFIo4MRJiMURbmAqXYkYUPI0s

###
GET http://localhost:8090/events/latest HTTP/1.1
user:kirill
###
POST http://localhost:8090/events HTTP/1.1
Content-Type: application/json
user: Kirill

[
  {
    "id": 0,
    "action": "Test",
    "oldState": "Test",
    "newState": "State Neu",
    "trigger": "Trigger Test",
    "timestamp": "2020-10-10"
  }
]

###

POST http://localhost:8090/events HTTP/1.1
Content-Type: application/json
user: Kirill

[
  {
    "id": 0,
    "oldState": "Test 2",
    "newState": "State Neu 2",
    "trigger": "Trigger Test 2",
    "timestamp": "2020-10-10"
  },
  {
    "id": 0,
    "action": "Test 3",
    "oldState": "Test 3",
    "newState": "State Neu 3",
    "trigger": "Trigger Test 3",
    "timestamp": "2020-10-10"
  }
]

###
POST http://localhost:8090/events HTTP/1.1
Content-Type: application/json
user: Kirill
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJLaXJpbGw1IiwiYXV0aCI6eyJhdXRob3JpdHkiOiJPRkZJQ0VfV09SS0VSIn0sImlhdCI6MTYxMTA3NzE1OCwiZXhwIjoxNjExMDgwNzU4fQ.P0retkczHq7TtisI7IwFIo4MRJiMURbmAqXYkYUPI0s

[]

# Sensordata

###
# wird von Spring automatisch erstellt
GET http://localhost:8090/sensorDatas HTTP/1.1
Content-Type: application/json
###
# unser RestController
GET http://localhost:8090/sensors HTTP/1.1
Content-Type: application/json

# /auth
####
POST http://localhost:8090/auth/register HTTP/1.1
Content-Type: application/json

{ 
  "name": "Kirill5",
  "password": "Kirill5",
  "role": "OFFICE_WORKER"
}

####
GET http://localhost:8090/events HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJLaXJpbGw1IiwiYXV0aCI6eyJhdXRob3JpdHkiOiJPRkZJQ0VfV09SS0VSIn0sImlhdCI6MTYxMDY1NDMxNSwiZXhwIjoxNjEwNjU3OTE1fQ.LADlsTRnN9b5FfFppc8YDf4m9AfReiUrjec3euFYhsQ

###
POST http://localhost:8090/events HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJLaXJpbGw1IiwiYXV0aCI6eyJhdXRob3JpdHkiOiJPRkZJQ0VfV09SS0VSIn0sImlhdCI6MTYxMDY1NDMxNSwiZXhwIjoxNjEwNjU3OTE1fQ.LADlsTRnN9b5FfFppc8YDf4m9AfReiUrjec3euFYhs
user: Kirill

[
  {
    "id": 0,
    "oldState": "Test 2",
    "action": "Action 2",
    "newState": "State Neu 2",
    "trigger": "Trigger Test 2",
    "timestamp": "2020-10-10"
  },
  {
    "id": 0,
    "action": "Test 3",
    "oldState": "Test 3",
    "newState": "State Neu 3",
    "trigger": "Trigger Test 3",
    "timestamp": "2020-10-10"
  }
]

###
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{ 
  "name": "Kirill5",
  "password": "Kirill5"
}