#define SECRET_SSID "<YOUR SSID>"
#define SECRET_PASS "<YOUR SSID PASSWORD>"

#define HOSTNAME "SENSOR_PROTOTYPE"

#define MQTT_HOST "<MQTT BROKER ADDRESS>"
#define MQTT_PORT 1884
#define MQTT_USER "<MQTT USERNAME>"
#define MQTT_PASS "<MQTT PASSWORD>"

#define MQTT_SUB_TOPIC "/test"
#define MQTT_PUB_TOPIC "/test"
